/**
 * Emits idempotent SQL that loads the SYNTHETIC demo dataset into the Supabase schema
 * (venues / activities / occurrences / availability_snapshots / source_records).
 *   npx tsx scripts/export-demo-sql.ts [startIso] [days] > seed_demo.sql
 * Every source record is data_permission_status='synthetic', so the UI keeps the DEMO label.
 * Re-running is safe (ON CONFLICT DO NOTHING / snapshot only when missing).
 */
import { buildDemoCandidates } from "../src/demo/demoData";
import { addMinutes } from "../src/domain/time";
import type { Candidate } from "../src/domain/types";

const start = process.argv[2] ?? new Date().toISOString();
const days = Number(process.argv[3] ?? 14);

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return `array[${v.map(q).join(",")}]::text[]`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const byId = new Map<string, Candidate>();
for (let d = 0; d < days; d++) {
  for (const c of buildDemoCandidates(addMinutes(start, d * 24 * 60), 24)) {
    // Ended or bad-geocode records are kept: the engine rejects them visibly, which is part of the demo.
    if (!byId.has(c.occurrenceId)) byId.set(c.occurrenceId, c);
  }
}

const out: string[] = ["-- CityGap SYNTHETIC demo data (not real events). Generated by scripts/export-demo-sql.ts", "begin;"];
const venues = new Set<string>();
const activities = new Set<string>();
for (const c of byId.values()) {
  const v = c.venue;
  // Records with an invalid 0,0 geocode stay out of the DB (the CHECK keeps lat/lng paired; 0,0 is legal SQL but meaningless).
  if (!venues.has(v.id)) {
    venues.add(v.id);
    out.push(
      `insert into public.venues (id,name,lat,lng,address,timezone,source_metadata) values (${q(v.id)},${q(v.name)},${q(v.lat)},${q(v.lng)},${q(v.address)},${q(v.timezone)},'{"source":"citygap-demo"}'::jsonb) on conflict (id) do nothing;`,
    );
  }
  if (!activities.has(c.activityId)) {
    activities.add(c.activityId);
    out.push(
      `insert into public.activities (id,title,kind,category,short_summary,duration_min_minutes,duration_max_minutes,venue_id,status,source_url,requires_booking) values (${q(c.activityId)},${q(c.title)},${q(c.kind)},${q(c.categories)},${q(c.shortSummary)},${q(c.durationMinMinutes)},${q(c.durationMaxMinutes)},${q(v.id)},'active',${q(c.source.url)},${q(c.requiresBooking)}) on conflict (id) do nothing;`,
    );
  }
  out.push(
    `insert into public.occurrences (id,activity_id,starts_at_utc,ends_at_utc,original_timezone,end_time_quality,cancellation_status) values (${q(c.occurrenceId)},${q(c.activityId)},${q(c.startsAt)},${q(c.endsAt)},${q(c.originalTimezone)},${q(c.endTimeQuality)},${q(c.cancellationStatus)}) on conflict (id) do nothing;`,
  );
  const a = c.availability;
  out.push(
    `insert into public.availability_snapshots (occurrence_id,booking_state,verified_at,expires_at,verification_source) select ${q(c.occurrenceId)},${q(a.state)},${q(a.verifiedAt)},${q(a.expiresAt)},${q(a.verificationSource)} where not exists (select 1 from public.availability_snapshots where occurrence_id=${q(c.occurrenceId)});`,
  );
  out.push(
    `insert into public.source_records (source_name,external_id,occurrence_id,source_url,data_permission_status,last_source_update,raw_hash) values (${q(c.source.name)},${q(c.source.externalId)},${q(c.occurrenceId)},${q(c.source.url)},'synthetic',${q(c.source.lastSourceUpdate)},'demo') on conflict (source_name,external_id) do nothing;`,
  );
}
out.push("commit;");
console.log(out.join("\n"));
console.error(`venues=${venues.size} activities=${activities.size} occurrences=${byId.size}`);
